### PR TITLE
Fixes for JSON api formatted data

### PR DESCRIPTION
**Pull request by jrjohnson**
Two changes:
1. When there are no matching entities return name: [] instead of just []
2. Submitted data is keyed by the resource name

I see there is a command flag --resource which I think is for the JSON api stuff, but I didn't see how to scope these templates to that flag.  Is that enabled?

### CODE REVIEW

**Comment by jrjohnson** [comment]
Don't merge this yet, I'm fixing some code style problem..

**Comment by vpassapera** [comment]
Yeah, it is enabled. In the generator you should see a render function that passes variables to the templates ($resource should be the one you're looking for).

Thanks!

**Comment by vpassapera** [comment]
Is this ready to be merged?

**Comment by jrjohnson** [comment]
Yes.  Unless you want me to differentiate the response based on the $resource option.  It wasn't happening before so its not a regression, but I should have some time Friday to add that.

**Comment by vpassapera** [comment]
I'll do it in the refactoring branch. Thanks!

**Pull request merged**
