### PR TITLE
Use seperate data transformers for single and many relations

### PR DESCRIPTION
**Pull request by jrjohnson**
I wasn't able to reliable determine whether a particular relationship was manyToMany or manyToOne in the FormType.php.twig.  I tried using the 'type' key on the field, but something wasn't working.  The generates all of the forms as if they were a single entity relationship.  If it isn't possible to parse on type then maybe we can just document that a manual review of forms is appropriate?

I also changed the name of the form for restfull generation.  That ensures data is wrapped correctly in an object of the same name.

### CODE REVIEW

**Comment by vpassapera** [comment]
Very cool will be merging now.. Btw how did you try to determine those relationships?

Did you take a look at https://github.com/vpassapera/sfprojectgeneratorbundle/blob/develop/Generator/Generator.php#L119

This is great though.

Thanks.

**Comment by jrjohnson** [comment]
Yea, thats where I was checking against the constants and trying to set a isMany type on the field.  But it didn't seem to be making it into the template and I couldn't sort out why.  I also tried just checking the type that is being set there against integers in the template, but it was always a many relationship.  I think it probably has something to do with;
https://github.com/vpassapera/sfprojectgeneratorbundle/blob/develop/Generator/Generator.php#L132
But I wasn't able to follow why you were removing those from the array.

**Comment by vpassapera** [comment]
That code is from the original version that wasn't able to handle certain
types of relationships. We can probably remove that though.

--
*Victor Passapera*
*Software Architect*


On Fri, Feb 20, 2015 at 12:51 PM, Jonathan Johnson <notifications@github.com

**Comment by jrjohnson** [comment]
OK, I will hopefully have some time to take another pass this weekend.  I was also thinking about doing forms as services and maybe generating html for the controllers as well.

**Comment by vpassapera** [comment]
:O

--
*Victor Passapera*
*Software Architect*

**Comment by vpassapera** [comment]
XD

--
*Victor Passapera*
*Software Architect*

**Comment by vpassapera** [comment]
I'm working on my worstation hardware today, but as soon as it's back up i'll be working on the refactor branch again today. I've also created another project called LeTraits which is meant to supplement this as a generic repo for traits. I'll be using that, this and a new project I've created to test out the refactor branch and clear up any kinks I run into.

Let me know if you need any help. I'll be on IRC as well.

**Pull request merged**
